Add interactive setup menu
elastic/snyk-github-issue-creator pull request #267
Opened 2020-11-19 19:37 UTC by watson

Sorry for this massive PR 😅 Feel free to use it as a starting point for a discussion!

This PR adds two features which helps setting up the program (what we today use the environment variables and the command line options for):

1. It adds an interactive prompt where the user can enter the config options in the console.
1. It asks the user if they want to save the config options to be re-used next time the program is run.

Besides `--stdin`, the other config options are no longer supported (I wasn't sure if `--stdin` was still needed to I left it for now).

2020-11-20 16:38 UTC, pierre-ernst requested changes
Thanks so much for contributing this PR
I'm also looking for volunteers to write unit tests, the more and more we change big chunks of code, the less confident I am that we are not breaking any features...

2020-11-20 16:38 UTC, pierre-ernst commented on cli/config.js
> +    if (conf.save) config.set(conf);
This is the exact reason why I wanted to use $env vars to store API tokens :-)
It is against security best practices to persist these tokens on FS...
Maybe we could offer an option to save everything **BUT** the 2 tokens?

2020-11-20 16:38 UTC, pierre-ernst commented on cli/config.js
> +        }
I confirm that this feature is still actively used (internally) when the output of the Snyk CLI is piped to this application

2020-11-23 12:13 UTC, watson commented on cli/config.js
> +    if (conf.save) config.set(conf);
One of my goals of this PR was to make the utility easier to use, in that I always forgot where to find these tokens between each time I ran it (especially the GitHub token was a pain because it needed to be re-generated each time). So I ended up not using this utility as much as I probably should 😅 

The tokens (and everything else) are stored in a file on disk under the users home directory (`~/.config/configstore/snyk-github-issue-creator.json`), with `600` permissions, so they are only accessible to the user who saved them. If this user is compromised, an attacker will also have access to the command history etc where these tokens most likely will be stored in case you type them in manually in the console.

I assume both the GitHub and Snyk CLI uses a similar storage mechanism to store their tokens, so I don't think we're any worse off in this scenario.

But please let me know if I've overlooked an attack-vector here 😃

2020-11-24 00:46 UTC, pierre-ernst commented on cli/config.js
> +    if (conf.save) config.set(conf);
Fair enough, it is always a tradeoff between useability (==adoption) and more security.
But here is my (other) concern:
Personally, I generate GH tickets for several projects, all having different org Id and project Id, so I would like to either:

- have the option to enter the parameters as arguments
- read from a local config file (not stored in the user's home but in the project folder)

2020-11-24 17:11 UTC, watson commented on cli/config.js
> +    if (conf.save) config.set(conf);
Good idea. I'll update the PR to allow that use-case

2020-11-24 21:44 UTC, watson commented on cli/config.js
> +    if (conf.save) config.set(conf);
@pierre-ernst do we need to utility to work in a non TTY environment - i.e. without accepting any user-input via the `enquirer` UI?

2020-11-25 00:57 UTC, pierre-ernst commented on cli/config.js
> +    if (conf.save) config.set(conf);
No I don't think so

2020-12-03 16:32 UTC, watson commented on cli/config.js
> +    if (conf.save) config.set(conf);
Fixed

2020-12-03 19:50 UTC, pierre-ernst approved these changes
Thanks so much

2020-12-03 19:50 UTC, merged